### ISSUE TITLE
Quebrar em componentes menores.

### ISSUE THREAD

**Issue by matheusgr** [JonathanAllisson/Webdev#10]
https://github.com/JonathanAllisson/Webdev/blob/a51bd55c54e83360e083d710c31bfdfa0128be24/front/src/pages/Pet/index.js#L57-L110

é ok quebrar em componentes menores, mesmo que não sejam reutilizáveis, para dar mais clareza e escopar melhor a página. aqui, certamente vc pode quebrar no panel e nos comments, por exemplo. ajuda a diminuir o tamanho do elemento (e dependências).

**Comment by JonathanAllisson** [comment]
Opa Gaudêncio, muito obrigado pelo feedback, em relação aos comentários já estava ciente que o corrento seria realmente criar outro componente pra ele ate pra que quando alguém realizasse um comentário o jsx completo da página fosse recarregado. Separei ele em outro componente e os dados do panel em outro componente tbm, vlw :D
