### ISSUE TITLE
Colocar na classe de teste correta

### ISSUE THREAD

**Issue by matheusgr** [JonathanAllisson/Webdev#11]
https://github.com/JonathanAllisson/Webdev/blob/a51bd55c54e83360e083d710c31bfdfa0128be24/front/src/tests/app.test.js

Renomear para PetCard.test.js e colocar em uma pasta tests ou __tests__ no diretório associado ao componente.

**Comment by JonathanAllisson** [comment]
Opa, havia me esquecido de renomear 😅

**Comment by JonathanAllisson** [comment]
corrigido
