### ISSUE TITLE
Sqlite usage

### ISSUE THREAD

**Issue by gabrielfern** [JonathanAllisson/Webdev#12]
Ola, gostei da ideia de usar sqlite. Parece apropriado para o contexto, e deixa
mais simples o projeto.
Queria sugerir algumas coisas:
1. Manter o arquivo do db (.sqlite) fora do git. Talvez uma maneira mais recomendada de popular o db inicialmente
seja usando _seeds_, caso tu se interesse da uma olhada na documentacao do knex por seeds
2. Percebi que em modo _production_ tais usando o postgres, mas nao tem o pg como dependencia no
package.json. Possa ser que nao funcione.

Queria deixar como dica que uma forma facil e legal de visualizar um .sqlite eh usando o site https://inloop.github.io/sqlite-viewer

**Comment by JonathanAllisson** [comment]
Olá, eu reconheço que o mais correto seria usar seeds para popular o bd como vc disse, apenas não fiz isso pois o backend não é tanto o foco da disciplina então quis deixar mais fácil a avaliação dos outros alunos, mas se der tempo, vou fazer essa alteração sim. Sobre o production, vlw por lembrar, até o momento não sei se vou fazer deploy ou não da aplicação, mas já estou ciente a respeito e também obrigado pelo visualizador de sqlite, ele parece ser bem útil e eu não o conhecia. Vlw pelo feedback geral.

**Comment by JonathanAllisson** [comment]
Feito :D
