### ISSUE TITLE
Sugestão de profile foto

### ISSUE THREAD

**Issue by oliveirosnt** [JonathanAllisson/Webdev#9]
Foi difícil arrumar uma correção ou sugestão pra dar, pq tá muito bem implementado :D 

Mas uma boa poderia ser adicionar um caminho de foto de profile no tipo usuário pra ser puxado no GET e carregado no usuário pelo backend.

**Comment by JonathanAllisson** [comment]
Obrigado pelo elogio e pela sugestão, vai ficar como feature futura caso termine as obrigatórias antes
